import! [metadata, rule_hint=cxx.link] core_libs = libspirv-cross%liba{spirv-cross-core}
import? [rule_hint=cxx.link] glsl_libs = libspirv-cross%liba{spirv-cross-glsl}

have_glsl = $($core_libs: libspirv_cross.glsl)

exe{driver}: {hxx ixx txx cxx}{**} $glsl_libs testscript{**}
exe{driver}: file{c_api_test.spv}: test.input = true
./: exe{driver}: include = $have_glsl
